// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/booking/v1/booking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VehicleId         string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	StartDate         string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // RFC3339
	EndDate           string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // RFC3339
	PickupLocationId  string                 `protobuf:"bytes,5,opt,name=pickup_location_id,json=pickupLocationId,proto3" json:"pickup_location_id,omitempty"`
	DropoffLocationId string                 `protobuf:"bytes,6,opt,name=dropoff_location_id,json=dropoffLocationId,proto3" json:"dropoff_location_id,omitempty"`
	Notes             string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookingRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *CreateBookingRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateBookingRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateBookingRequest) GetPickupLocationId() string {
	if x != nil {
		return x.PickupLocationId
	}
	return ""
}

func (x *CreateBookingRequest) GetDropoffLocationId() string {
	if x != nil {
		return x.DropoffLocationId
	}
	return ""
}

func (x *CreateBookingRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type UpdateBookingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BookingId         string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	StartDate         *string                `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate           *string                `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	Notes             *string                `protobuf:"bytes,4,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	PickupLocationId  *string                `protobuf:"bytes,5,opt,name=pickup_location_id,json=pickupLocationId,proto3,oneof" json:"pickup_location_id,omitempty"`
	DropoffLocationId *string                `protobuf:"bytes,6,opt,name=dropoff_location_id,json=dropoffLocationId,proto3,oneof" json:"dropoff_location_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateBookingRequest) Reset() {
	*x = UpdateBookingRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingRequest) ProtoMessage() {}

func (x *UpdateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *UpdateBookingRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *UpdateBookingRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *UpdateBookingRequest) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *UpdateBookingRequest) GetPickupLocationId() string {
	if x != nil && x.PickupLocationId != nil {
		return *x.PickupLocationId
	}
	return ""
}

func (x *UpdateBookingRequest) GetDropoffLocationId() string {
	if x != nil && x.DropoffLocationId != nil {
		return *x.DropoffLocationId
	}
	return ""
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelBookingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Refundable    bool                   `protobuf:"varint,2,opt,name=refundable,proto3" json:"refundable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelBookingResponse) GetRefundable() bool {
	if x != nil {
		return x.Refundable
	}
	return false
}

type ListUserBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // filter: "", "pending", "confirmed", "active", "completed", "cancelled"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserBookingsRequest) Reset() {
	*x = ListUserBookingsRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserBookingsRequest) ProtoMessage() {}

func (x *ListUserBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListUserBookingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserBookingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserBookingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserBookingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserBookingsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListUserBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserBookingsResponse) Reset() {
	*x = ListUserBookingsResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserBookingsResponse) ProtoMessage() {}

func (x *ListUserBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListUserBookingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *ListUserBookingsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CalculatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePriceRequest) Reset() {
	*x = CalculatePriceRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceRequest) ProtoMessage() {}

func (x *CalculatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceRequest.ProtoReflect.Descriptor instead.
func (*CalculatePriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{7}
}

func (x *CalculatePriceRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *CalculatePriceRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CalculatePriceRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CalculatePriceResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BasePrice          float64                `protobuf:"fixed64,1,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	SeasonalMultiplier float64                `protobuf:"fixed64,2,opt,name=seasonal_multiplier,json=seasonalMultiplier,proto3" json:"seasonal_multiplier,omitempty"`
	TotalPrice         float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	RentalDays         int32                  `protobuf:"varint,4,opt,name=rental_days,json=rentalDays,proto3" json:"rental_days,omitempty"`
	Currency           string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PricingTierId      string                 `protobuf:"bytes,6,opt,name=pricing_tier_id,json=pricingTierId,proto3" json:"pricing_tier_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CalculatePriceResponse) Reset() {
	*x = CalculatePriceResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceResponse) ProtoMessage() {}

func (x *CalculatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceResponse.ProtoReflect.Descriptor instead.
func (*CalculatePriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{8}
}

func (x *CalculatePriceResponse) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetSeasonalMultiplier() float64 {
	if x != nil {
		return x.SeasonalMultiplier
	}
	return 0
}

func (x *CalculatePriceResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetRentalDays() int32 {
	if x != nil {
		return x.RentalDays
	}
	return 0
}

func (x *CalculatePriceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CalculatePriceResponse) GetPricingTierId() string {
	if x != nil {
		return x.PricingTierId
	}
	return ""
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{9}
}

func (x *CheckAvailabilityRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Conflicts     []*ConflictingBooking  `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{10}
}

func (x *CheckAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckAvailabilityResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckAvailabilityResponse) GetConflicts() []*ConflictingBooking {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type ConflictingBooking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictingBooking) Reset() {
	*x = ConflictingBooking{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictingBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictingBooking) ProtoMessage() {}

func (x *ConflictingBooking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictingBooking.ProtoReflect.Descriptor instead.
func (*ConflictingBooking) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{11}
}

func (x *ConflictingBooking) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ConflictingBooking) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ConflictingBooking) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ExtendBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	NewEndDate    string                 `protobuf:"bytes,2,opt,name=new_end_date,json=newEndDate,proto3" json:"new_end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendBookingRequest) Reset() {
	*x = ExtendBookingRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendBookingRequest) ProtoMessage() {}

func (x *ExtendBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendBookingRequest.ProtoReflect.Descriptor instead.
func (*ExtendBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{12}
}

func (x *ExtendBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ExtendBookingRequest) GetNewEndDate() string {
	if x != nil {
		return x.NewEndDate
	}
	return ""
}

type GetActivePricingTiersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VehicleCategory string                 `protobuf:"bytes,1,opt,name=vehicle_category,json=vehicleCategory,proto3" json:"vehicle_category,omitempty"` // optional filter
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetActivePricingTiersRequest) Reset() {
	*x = GetActivePricingTiersRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivePricingTiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivePricingTiersRequest) ProtoMessage() {}

func (x *GetActivePricingTiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivePricingTiersRequest.ProtoReflect.Descriptor instead.
func (*GetActivePricingTiersRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{13}
}

func (x *GetActivePricingTiersRequest) GetVehicleCategory() string {
	if x != nil {
		return x.VehicleCategory
	}
	return ""
}

type GetActivePricingTiersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tiers         []*PricingTier         `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivePricingTiersResponse) Reset() {
	*x = GetActivePricingTiersResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivePricingTiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivePricingTiersResponse) ProtoMessage() {}

func (x *GetActivePricingTiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivePricingTiersResponse.ProtoReflect.Descriptor instead.
func (*GetActivePricingTiersResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{14}
}

func (x *GetActivePricingTiersResponse) GetTiers() []*PricingTier {
	if x != nil {
		return x.Tiers
	}
	return nil
}

type ProcessRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	RefundAmount  float64                `protobuf:"fixed64,2,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRefundRequest) Reset() {
	*x = ProcessRefundRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRefundRequest) ProtoMessage() {}

func (x *ProcessRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRefundRequest.ProtoReflect.Descriptor instead.
func (*ProcessRefundRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessRefundRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ProcessRefundRequest) GetRefundAmount() float64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *ProcessRefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ProcessRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRefundResponse) Reset() {
	*x = ProcessRefundResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRefundResponse) ProtoMessage() {}

func (x *ProcessRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRefundResponse.ProtoReflect.Descriptor instead.
func (*ProcessRefundResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessRefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *ProcessRefundResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessRefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessRefundResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBookingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingHistoryRequest) Reset() {
	*x = GetBookingHistoryRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingHistoryRequest) ProtoMessage() {}

func (x *GetBookingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetBookingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{17}
}

func (x *GetBookingHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBookingHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBookingHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetBookingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*BookingHistoryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingHistoryResponse) Reset() {
	*x = GetBookingHistoryResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingHistoryResponse) ProtoMessage() {}

func (x *GetBookingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetBookingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{18}
}

func (x *GetBookingHistoryResponse) GetEntries() []*BookingHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetBookingHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BookingHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	Events        []string               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"` // e.g. ["created", "confirmed", "completed"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingHistoryEntry) Reset() {
	*x = BookingHistoryEntry{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingHistoryEntry) ProtoMessage() {}

func (x *BookingHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingHistoryEntry.ProtoReflect.Descriptor instead.
func (*BookingHistoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{19}
}

func (x *BookingHistoryEntry) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *BookingHistoryEntry) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type ConfirmBookingPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentRef    string                 `protobuf:"bytes,3,opt,name=payment_ref,json=paymentRef,proto3" json:"payment_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingPaymentRequest) Reset() {
	*x = ConfirmBookingPaymentRequest{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingPaymentRequest) ProtoMessage() {}

func (x *ConfirmBookingPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBookingPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{20}
}

func (x *ConfirmBookingPaymentRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ConfirmBookingPaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ConfirmBookingPaymentRequest) GetPaymentRef() string {
	if x != nil {
		return x.PaymentRef
	}
	return ""
}

type Booking struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VehicleId          string                 `protobuf:"bytes,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartDate          string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate            string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TotalPrice         float64                `protobuf:"fixed64,7,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Currency           string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	PickupLocationId   string                 `protobuf:"bytes,9,opt,name=pickup_location_id,json=pickupLocationId,proto3" json:"pickup_location_id,omitempty"`
	DropoffLocationId  string                 `protobuf:"bytes,10,opt,name=dropoff_location_id,json=dropoffLocationId,proto3" json:"dropoff_location_id,omitempty"`
	Notes              string                 `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	CancellationReason string                 `protobuf:"bytes,12,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	PaymentStatus      string                 `protobuf:"bytes,13,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	PaymentRef         string                 `protobuf:"bytes,14,opt,name=payment_ref,json=paymentRef,proto3" json:"payment_ref,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          int64                  `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{21}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Booking) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Booking) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Booking) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Booking) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Booking) GetPickupLocationId() string {
	if x != nil {
		return x.PickupLocationId
	}
	return ""
}

func (x *Booking) GetDropoffLocationId() string {
	if x != nil {
		return x.DropoffLocationId
	}
	return ""
}

func (x *Booking) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Booking) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

func (x *Booking) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *Booking) GetPaymentRef() string {
	if x != nil {
		return x.PaymentRef
	}
	return ""
}

func (x *Booking) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Booking) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{22}
}

func (x *BookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type PricingTier struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VehicleCategory    string                 `protobuf:"bytes,3,opt,name=vehicle_category,json=vehicleCategory,proto3" json:"vehicle_category,omitempty"`
	BaseDailyRate      float64                `protobuf:"fixed64,4,opt,name=base_daily_rate,json=baseDailyRate,proto3" json:"base_daily_rate,omitempty"`
	SeasonalMultiplier float64                `protobuf:"fixed64,5,opt,name=seasonal_multiplier,json=seasonalMultiplier,proto3" json:"seasonal_multiplier,omitempty"`
	SeasonStart        string                 `protobuf:"bytes,6,opt,name=season_start,json=seasonStart,proto3" json:"season_start,omitempty"` // "MM-DD"
	SeasonEnd          string                 `protobuf:"bytes,7,opt,name=season_end,json=seasonEnd,proto3" json:"season_end,omitempty"`       // "MM-DD"
	IsActive           bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PricingTier) Reset() {
	*x = PricingTier{}
	mi := &file_proto_booking_v1_booking_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingTier) ProtoMessage() {}

func (x *PricingTier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_v1_booking_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingTier.ProtoReflect.Descriptor instead.
func (*PricingTier) Descriptor() ([]byte, []int) {
	return file_proto_booking_v1_booking_proto_rawDescGZIP(), []int{23}
}

func (x *PricingTier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PricingTier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PricingTier) GetVehicleCategory() string {
	if x != nil {
		return x.VehicleCategory
	}
	return ""
}

func (x *PricingTier) GetBaseDailyRate() float64 {
	if x != nil {
		return x.BaseDailyRate
	}
	return 0
}

func (x *PricingTier) GetSeasonalMultiplier() float64 {
	if x != nil {
		return x.SeasonalMultiplier
	}
	return 0
}

func (x *PricingTier) GetSeasonStart() string {
	if x != nil {
		return x.SeasonStart
	}
	return ""
}

func (x *PricingTier) GetSeasonEnd() string {
	if x != nil {
		return x.SeasonEnd
	}
	return ""
}

func (x *PricingTier) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PricingTier) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PricingTier) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_proto_booking_v1_booking_proto protoreflect.FileDescriptor

const file_proto_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/booking/v1/booking.proto\x12\n" +
	"booking.v1\"\xfc\x01\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12,\n" +
	"\x12pickup_location_id\x18\x05 \x01(\tR\x10pickupLocationId\x12.\n" +
	"\x13dropoff_location_id\x18\x06 \x01(\tR\x11dropoffLocationId\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"2\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"\xd1\x02\n" +
	"\x14UpdateBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\"\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tH\x00R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x03 \x01(\tH\x01R\aendDate\x88\x01\x01\x12\x19\n" +
	"\x05notes\x18\x04 \x01(\tH\x02R\x05notes\x88\x01\x01\x121\n" +
	"\x12pickup_location_id\x18\x05 \x01(\tH\x03R\x10pickupLocationId\x88\x01\x01\x123\n" +
	"\x13dropoff_location_id\x18\x06 \x01(\tH\x04R\x11dropoffLocationId\x88\x01\x01B\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\b\n" +
	"\x06_notesB\x15\n" +
	"\x13_pickup_location_idB\x16\n" +
	"\x14_dropoff_location_id\"M\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Q\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"refundable\x18\x02 \x01(\bR\n" +
	"refundable\"{\n" +
	"\x17ListUserBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"a\n" +
	"\x18ListUserBookingsResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.booking.v1.BookingR\bbookings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"p\n" +
	"\x15CalculatePriceRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xee\x01\n" +
	"\x16CalculatePriceResponse\x12\x1d\n" +
	"\n" +
	"base_price\x18\x01 \x01(\x01R\tbasePrice\x12/\n" +
	"\x13seasonal_multiplier\x18\x02 \x01(\x01R\x12seasonalMultiplier\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\x12\x1f\n" +
	"\vrental_days\x18\x04 \x01(\x05R\n" +
	"rentalDays\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12&\n" +
	"\x0fpricing_tier_id\x18\x06 \x01(\tR\rpricingTierId\"s\n" +
	"\x18CheckAvailabilityRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\x8f\x01\n" +
	"\x19CheckAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12<\n" +
	"\tconflicts\x18\x03 \x03(\v2\x1e.booking.v1.ConflictingBookingR\tconflicts\"m\n" +
	"\x12ConflictingBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"W\n" +
	"\x14ExtendBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12 \n" +
	"\fnew_end_date\x18\x02 \x01(\tR\n" +
	"newEndDate\"I\n" +
	"\x1cGetActivePricingTiersRequest\x12)\n" +
	"\x10vehicle_category\x18\x01 \x01(\tR\x0fvehicleCategory\"N\n" +
	"\x1dGetActivePricingTiersResponse\x12-\n" +
	"\x05tiers\x18\x01 \x03(\v2\x17.booking.v1.PricingTierR\x05tiers\"r\n" +
	"\x14ProcessRefundRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12#\n" +
	"\rrefund_amount\x18\x02 \x01(\x01R\frefundAmount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"~\n" +
	"\x15ProcessRefundResponse\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"d\n" +
	"\x18GetBookingHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"l\n" +
	"\x19GetBookingHistoryResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.booking.v1.BookingHistoryEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\\\n" +
	"\x13BookingHistoryEntry\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.booking.v1.BookingR\abooking\x12\x16\n" +
	"\x06events\x18\x02 \x03(\tR\x06events\"\x85\x01\n" +
	"\x1cConfirmBookingPaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vpayment_ref\x18\x03 \x01(\tR\n" +
	"paymentRef\"\x8b\x04\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\tR\tvehicleId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1f\n" +
	"\vtotal_price\x18\a \x01(\x01R\n" +
	"totalPrice\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12,\n" +
	"\x12pickup_location_id\x18\t \x01(\tR\x10pickupLocationId\x12.\n" +
	"\x13dropoff_location_id\x18\n" +
	" \x01(\tR\x11dropoffLocationId\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\x12/\n" +
	"\x13cancellation_reason\x18\f \x01(\tR\x12cancellationReason\x12%\n" +
	"\x0epayment_status\x18\r \x01(\tR\rpaymentStatus\x12\x1f\n" +
	"\vpayment_ref\x18\x0e \x01(\tR\n" +
	"paymentRef\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\x03R\tupdatedAt\"@\n" +
	"\x0fBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.booking.v1.BookingR\abooking\"\xd2\x02\n" +
	"\vPricingTier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10vehicle_category\x18\x03 \x01(\tR\x0fvehicleCategory\x12&\n" +
	"\x0fbase_daily_rate\x18\x04 \x01(\x01R\rbaseDailyRate\x12/\n" +
	"\x13seasonal_multiplier\x18\x05 \x01(\x01R\x12seasonalMultiplier\x12!\n" +
	"\fseason_start\x18\x06 \x01(\tR\vseasonStart\x12\x1d\n" +
	"\n" +
	"season_end\x18\a \x01(\tR\tseasonEnd\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt2\xd8\b\n" +
	"\x0eBookingService\x12P\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a\x1b.booking.v1.BookingResponse\"\x00\x12J\n" +
	"\n" +
	"GetBooking\x12\x1d.booking.v1.GetBookingRequest\x1a\x1b.booking.v1.BookingResponse\"\x00\x12P\n" +
	"\rUpdateBooking\x12 .booking.v1.UpdateBookingRequest\x1a\x1b.booking.v1.BookingResponse\"\x00\x12V\n" +
	"\rCancelBooking\x12 .booking.v1.CancelBookingRequest\x1a!.booking.v1.CancelBookingResponse\"\x00\x12_\n" +
	"\x10ListUserBookings\x12#.booking.v1.ListUserBookingsRequest\x1a$.booking.v1.ListUserBookingsResponse\"\x00\x12Y\n" +
	"\x0eCalculatePrice\x12!.booking.v1.CalculatePriceRequest\x1a\".booking.v1.CalculatePriceResponse\"\x00\x12b\n" +
	"\x11CheckAvailability\x12$.booking.v1.CheckAvailabilityRequest\x1a%.booking.v1.CheckAvailabilityResponse\"\x00\x12P\n" +
	"\rExtendBooking\x12 .booking.v1.ExtendBookingRequest\x1a\x1b.booking.v1.BookingResponse\"\x00\x12n\n" +
	"\x15GetActivePricingTiers\x12(.booking.v1.GetActivePricingTiersRequest\x1a).booking.v1.GetActivePricingTiersResponse\"\x00\x12V\n" +
	"\rProcessRefund\x12 .booking.v1.ProcessRefundRequest\x1a!.booking.v1.ProcessRefundResponse\"\x00\x12b\n" +
	"\x11GetBookingHistory\x12$.booking.v1.GetBookingHistoryRequest\x1a%.booking.v1.GetBookingHistoryResponse\"\x00\x12`\n" +
	"\x15ConfirmBookingPayment\x12(.booking.v1.ConfirmBookingPaymentRequest\x1a\x1b.booking.v1.BookingResponse\"\x00B?Z=github.com/nurashi/car-rental-booking/internal/api/grpc/pb;pbb\x06proto3"

var (
	file_proto_booking_v1_booking_proto_rawDescOnce sync.Once
	file_proto_booking_v1_booking_proto_rawDescData []byte
)

func file_proto_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_v1_booking_proto_rawDesc), len(file_proto_booking_v1_booking_proto_rawDesc)))
	})
	return file_proto_booking_v1_booking_proto_rawDescData
}

var file_proto_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_booking_v1_booking_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),          // 0: booking.v1.CreateBookingRequest
	(*GetBookingRequest)(nil),             // 1: booking.v1.GetBookingRequest
	(*UpdateBookingRequest)(nil),          // 2: booking.v1.UpdateBookingRequest
	(*CancelBookingRequest)(nil),          // 3: booking.v1.CancelBookingRequest
	(*CancelBookingResponse)(nil),         // 4: booking.v1.CancelBookingResponse
	(*ListUserBookingsRequest)(nil),       // 5: booking.v1.ListUserBookingsRequest
	(*ListUserBookingsResponse)(nil),      // 6: booking.v1.ListUserBookingsResponse
	(*CalculatePriceRequest)(nil),         // 7: booking.v1.CalculatePriceRequest
	(*CalculatePriceResponse)(nil),        // 8: booking.v1.CalculatePriceResponse
	(*CheckAvailabilityRequest)(nil),      // 9: booking.v1.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil),     // 10: booking.v1.CheckAvailabilityResponse
	(*ConflictingBooking)(nil),            // 11: booking.v1.ConflictingBooking
	(*ExtendBookingRequest)(nil),          // 12: booking.v1.ExtendBookingRequest
	(*GetActivePricingTiersRequest)(nil),  // 13: booking.v1.GetActivePricingTiersRequest
	(*GetActivePricingTiersResponse)(nil), // 14: booking.v1.GetActivePricingTiersResponse
	(*ProcessRefundRequest)(nil),          // 15: booking.v1.ProcessRefundRequest
	(*ProcessRefundResponse)(nil),         // 16: booking.v1.ProcessRefundResponse
	(*GetBookingHistoryRequest)(nil),      // 17: booking.v1.GetBookingHistoryRequest
	(*GetBookingHistoryResponse)(nil),     // 18: booking.v1.GetBookingHistoryResponse
	(*BookingHistoryEntry)(nil),           // 19: booking.v1.BookingHistoryEntry
	(*ConfirmBookingPaymentRequest)(nil),  // 20: booking.v1.ConfirmBookingPaymentRequest
	(*Booking)(nil),                       // 21: booking.v1.Booking
	(*BookingResponse)(nil),               // 22: booking.v1.BookingResponse
	(*PricingTier)(nil),                   // 23: booking.v1.PricingTier
}
var file_proto_booking_v1_booking_proto_depIdxs = []int32{
	21, // 0: booking.v1.ListUserBookingsResponse.bookings:type_name -> booking.v1.Booking
	11, // 1: booking.v1.CheckAvailabilityResponse.conflicts:type_name -> booking.v1.ConflictingBooking
	23, // 2: booking.v1.GetActivePricingTiersResponse.tiers:type_name -> booking.v1.PricingTier
	19, // 3: booking.v1.GetBookingHistoryResponse.entries:type_name -> booking.v1.BookingHistoryEntry
	21, // 4: booking.v1.BookingHistoryEntry.booking:type_name -> booking.v1.Booking
	21, // 5: booking.v1.BookingResponse.booking:type_name -> booking.v1.Booking
	0,  // 6: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	1,  // 7: booking.v1.BookingService.GetBooking:input_type -> booking.v1.GetBookingRequest
	2,  // 8: booking.v1.BookingService.UpdateBooking:input_type -> booking.v1.UpdateBookingRequest
	3,  // 9: booking.v1.BookingService.CancelBooking:input_type -> booking.v1.CancelBookingRequest
	5,  // 10: booking.v1.BookingService.ListUserBookings:input_type -> booking.v1.ListUserBookingsRequest
	7,  // 11: booking.v1.BookingService.CalculatePrice:input_type -> booking.v1.CalculatePriceRequest
	9,  // 12: booking.v1.BookingService.CheckAvailability:input_type -> booking.v1.CheckAvailabilityRequest
	12, // 13: booking.v1.BookingService.ExtendBooking:input_type -> booking.v1.ExtendBookingRequest
	13, // 14: booking.v1.BookingService.GetActivePricingTiers:input_type -> booking.v1.GetActivePricingTiersRequest
	15, // 15: booking.v1.BookingService.ProcessRefund:input_type -> booking.v1.ProcessRefundRequest
	17, // 16: booking.v1.BookingService.GetBookingHistory:input_type -> booking.v1.GetBookingHistoryRequest
	20, // 17: booking.v1.BookingService.ConfirmBookingPayment:input_type -> booking.v1.ConfirmBookingPaymentRequest
	22, // 18: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.BookingResponse
	22, // 19: booking.v1.BookingService.GetBooking:output_type -> booking.v1.BookingResponse
	22, // 20: booking.v1.BookingService.UpdateBooking:output_type -> booking.v1.BookingResponse
	4,  // 21: booking.v1.BookingService.CancelBooking:output_type -> booking.v1.CancelBookingResponse
	6,  // 22: booking.v1.BookingService.ListUserBookings:output_type -> booking.v1.ListUserBookingsResponse
	8,  // 23: booking.v1.BookingService.CalculatePrice:output_type -> booking.v1.CalculatePriceResponse
	10, // 24: booking.v1.BookingService.CheckAvailability:output_type -> booking.v1.CheckAvailabilityResponse
	22, // 25: booking.v1.BookingService.ExtendBooking:output_type -> booking.v1.BookingResponse
	14, // 26: booking.v1.BookingService.GetActivePricingTiers:output_type -> booking.v1.GetActivePricingTiersResponse
	16, // 27: booking.v1.BookingService.ProcessRefund:output_type -> booking.v1.ProcessRefundResponse
	18, // 28: booking.v1.BookingService.GetBookingHistory:output_type -> booking.v1.GetBookingHistoryResponse
	22, // 29: booking.v1.BookingService.ConfirmBookingPayment:output_type -> booking.v1.BookingResponse
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_booking_v1_booking_proto_init() }
func file_proto_booking_v1_booking_proto_init() {
	if File_proto_booking_v1_booking_proto != nil {
		return
	}
	file_proto_booking_v1_booking_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_v1_booking_proto_rawDesc), len(file_proto_booking_v1_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_v1_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_v1_booking_proto = out.File
	file_proto_booking_v1_booking_proto_goTypes = nil
	file_proto_booking_v1_booking_proto_depIdxs = nil
}
