// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/vehicle_inventory.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VehicleInventoryService_CreateVehicle_FullMethodName           = "/vehicle_inventory.VehicleInventoryService/CreateVehicle"
	VehicleInventoryService_GetVehicle_FullMethodName              = "/vehicle_inventory.VehicleInventoryService/GetVehicle"
	VehicleInventoryService_UpdateVehicle_FullMethodName           = "/vehicle_inventory.VehicleInventoryService/UpdateVehicle"
	VehicleInventoryService_DeleteVehicle_FullMethodName           = "/vehicle_inventory.VehicleInventoryService/DeleteVehicle"
	VehicleInventoryService_ListVehicles_FullMethodName            = "/vehicle_inventory.VehicleInventoryService/ListVehicles"
	VehicleInventoryService_UpdateVehicleStatus_FullMethodName     = "/vehicle_inventory.VehicleInventoryService/UpdateVehicleStatus"
	VehicleInventoryService_CreateLocation_FullMethodName          = "/vehicle_inventory.VehicleInventoryService/CreateLocation"
	VehicleInventoryService_GetLocation_FullMethodName             = "/vehicle_inventory.VehicleInventoryService/GetLocation"
	VehicleInventoryService_ListLocations_FullMethodName           = "/vehicle_inventory.VehicleInventoryService/ListLocations"
	VehicleInventoryService_CreateMaintenanceRecord_FullMethodName = "/vehicle_inventory.VehicleInventoryService/CreateMaintenanceRecord"
	VehicleInventoryService_GetMaintenanceRecord_FullMethodName    = "/vehicle_inventory.VehicleInventoryService/GetMaintenanceRecord"
	VehicleInventoryService_ListMaintenanceRecords_FullMethodName  = "/vehicle_inventory.VehicleInventoryService/ListMaintenanceRecords"
)

// VehicleInventoryServiceClient is the client API for VehicleInventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VehicleInventoryServiceClient interface {
	CreateVehicle(ctx context.Context, in *CreateVehicleRequest, opts ...grpc.CallOption) (*Vehicle, error)
	GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...grpc.CallOption) (*Vehicle, error)
	UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...grpc.CallOption) (*Vehicle, error)
	DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...grpc.CallOption) (*ListVehiclesResponse, error)
	UpdateVehicleStatus(ctx context.Context, in *UpdateVehicleStatusRequest, opts ...grpc.CallOption) (*Vehicle, error)
	CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*Location, error)
	GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*Location, error)
	ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error)
	CreateMaintenanceRecord(ctx context.Context, in *CreateMaintenanceRecordRequest, opts ...grpc.CallOption) (*MaintenanceRecord, error)
	GetMaintenanceRecord(ctx context.Context, in *GetMaintenanceRecordRequest, opts ...grpc.CallOption) (*MaintenanceRecord, error)
	ListMaintenanceRecords(ctx context.Context, in *ListMaintenanceRecordsRequest, opts ...grpc.CallOption) (*ListMaintenanceRecordsResponse, error)
}

type vehicleInventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVehicleInventoryServiceClient(cc grpc.ClientConnInterface) VehicleInventoryServiceClient {
	return &vehicleInventoryServiceClient{cc}
}

func (c *vehicleInventoryServiceClient) CreateVehicle(ctx context.Context, in *CreateVehicleRequest, opts ...grpc.CallOption) (*Vehicle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vehicle)
	err := c.cc.Invoke(ctx, VehicleInventoryService_CreateVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...grpc.CallOption) (*Vehicle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vehicle)
	err := c.cc.Invoke(ctx, VehicleInventoryService_GetVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...grpc.CallOption) (*Vehicle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vehicle)
	err := c.cc.Invoke(ctx, VehicleInventoryService_UpdateVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VehicleInventoryService_DeleteVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...grpc.CallOption) (*ListVehiclesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVehiclesResponse)
	err := c.cc.Invoke(ctx, VehicleInventoryService_ListVehicles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) UpdateVehicleStatus(ctx context.Context, in *UpdateVehicleStatusRequest, opts ...grpc.CallOption) (*Vehicle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vehicle)
	err := c.cc.Invoke(ctx, VehicleInventoryService_UpdateVehicleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*Location, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Location)
	err := c.cc.Invoke(ctx, VehicleInventoryService_CreateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*Location, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Location)
	err := c.cc.Invoke(ctx, VehicleInventoryService_GetLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLocationsResponse)
	err := c.cc.Invoke(ctx, VehicleInventoryService_ListLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) CreateMaintenanceRecord(ctx context.Context, in *CreateMaintenanceRecordRequest, opts ...grpc.CallOption) (*MaintenanceRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintenanceRecord)
	err := c.cc.Invoke(ctx, VehicleInventoryService_CreateMaintenanceRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) GetMaintenanceRecord(ctx context.Context, in *GetMaintenanceRecordRequest, opts ...grpc.CallOption) (*MaintenanceRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintenanceRecord)
	err := c.cc.Invoke(ctx, VehicleInventoryService_GetMaintenanceRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleInventoryServiceClient) ListMaintenanceRecords(ctx context.Context, in *ListMaintenanceRecordsRequest, opts ...grpc.CallOption) (*ListMaintenanceRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMaintenanceRecordsResponse)
	err := c.cc.Invoke(ctx, VehicleInventoryService_ListMaintenanceRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VehicleInventoryServiceServer is the server API for VehicleInventoryService service.
// All implementations must embed UnimplementedVehicleInventoryServiceServer
// for forward compatibility.
type VehicleInventoryServiceServer interface {
	CreateVehicle(context.Context, *CreateVehicleRequest) (*Vehicle, error)
	GetVehicle(context.Context, *GetVehicleRequest) (*Vehicle, error)
	UpdateVehicle(context.Context, *UpdateVehicleRequest) (*Vehicle, error)
	DeleteVehicle(context.Context, *DeleteVehicleRequest) (*emptypb.Empty, error)
	ListVehicles(context.Context, *ListVehiclesRequest) (*ListVehiclesResponse, error)
	UpdateVehicleStatus(context.Context, *UpdateVehicleStatusRequest) (*Vehicle, error)
	CreateLocation(context.Context, *CreateLocationRequest) (*Location, error)
	GetLocation(context.Context, *GetLocationRequest) (*Location, error)
	ListLocations(context.Context, *ListLocationsRequest) (*ListLocationsResponse, error)
	CreateMaintenanceRecord(context.Context, *CreateMaintenanceRecordRequest) (*MaintenanceRecord, error)
	GetMaintenanceRecord(context.Context, *GetMaintenanceRecordRequest) (*MaintenanceRecord, error)
	ListMaintenanceRecords(context.Context, *ListMaintenanceRecordsRequest) (*ListMaintenanceRecordsResponse, error)
	mustEmbedUnimplementedVehicleInventoryServiceServer()
}

// UnimplementedVehicleInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVehicleInventoryServiceServer struct{}

func (UnimplementedVehicleInventoryServiceServer) CreateVehicle(context.Context, *CreateVehicleRequest) (*Vehicle, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVehicle not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) GetVehicle(context.Context, *GetVehicleRequest) (*Vehicle, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVehicle not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) UpdateVehicle(context.Context, *UpdateVehicleRequest) (*Vehicle, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVehicle not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) DeleteVehicle(context.Context, *DeleteVehicleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVehicle not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) ListVehicles(context.Context, *ListVehiclesRequest) (*ListVehiclesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVehicles not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) UpdateVehicleStatus(context.Context, *UpdateVehicleStatusRequest) (*Vehicle, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVehicleStatus not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) CreateLocation(context.Context, *CreateLocationRequest) (*Location, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLocation not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) GetLocation(context.Context, *GetLocationRequest) (*Location, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLocation not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) ListLocations(context.Context, *ListLocationsRequest) (*ListLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLocations not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) CreateMaintenanceRecord(context.Context, *CreateMaintenanceRecordRequest) (*MaintenanceRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMaintenanceRecord not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) GetMaintenanceRecord(context.Context, *GetMaintenanceRecordRequest) (*MaintenanceRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMaintenanceRecord not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) ListMaintenanceRecords(context.Context, *ListMaintenanceRecordsRequest) (*ListMaintenanceRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMaintenanceRecords not implemented")
}
func (UnimplementedVehicleInventoryServiceServer) mustEmbedUnimplementedVehicleInventoryServiceServer() {
}
func (UnimplementedVehicleInventoryServiceServer) testEmbeddedByValue() {}

// UnsafeVehicleInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VehicleInventoryServiceServer will
// result in compilation errors.
type UnsafeVehicleInventoryServiceServer interface {
	mustEmbedUnimplementedVehicleInventoryServiceServer()
}

func RegisterVehicleInventoryServiceServer(s grpc.ServiceRegistrar, srv VehicleInventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedVehicleInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VehicleInventoryService_ServiceDesc, srv)
}

func _VehicleInventoryService_CreateVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).CreateVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_CreateVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).CreateVehicle(ctx, req.(*CreateVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_GetVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).GetVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_GetVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).GetVehicle(ctx, req.(*GetVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_UpdateVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).UpdateVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_UpdateVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).UpdateVehicle(ctx, req.(*UpdateVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_DeleteVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).DeleteVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_DeleteVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).DeleteVehicle(ctx, req.(*DeleteVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_ListVehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).ListVehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_ListVehicles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).ListVehicles(ctx, req.(*ListVehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_UpdateVehicleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVehicleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).UpdateVehicleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_UpdateVehicleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).UpdateVehicleStatus(ctx, req.(*UpdateVehicleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_CreateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).CreateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_CreateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).CreateLocation(ctx, req.(*CreateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_GetLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).GetLocation(ctx, req.(*GetLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_ListLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).ListLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_ListLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).ListLocations(ctx, req.(*ListLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_CreateMaintenanceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMaintenanceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).CreateMaintenanceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_CreateMaintenanceRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).CreateMaintenanceRecord(ctx, req.(*CreateMaintenanceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_GetMaintenanceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMaintenanceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).GetMaintenanceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_GetMaintenanceRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).GetMaintenanceRecord(ctx, req.(*GetMaintenanceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleInventoryService_ListMaintenanceRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMaintenanceRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleInventoryServiceServer).ListMaintenanceRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleInventoryService_ListMaintenanceRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleInventoryServiceServer).ListMaintenanceRecords(ctx, req.(*ListMaintenanceRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VehicleInventoryService_ServiceDesc is the grpc.ServiceDesc for VehicleInventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VehicleInventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vehicle_inventory.VehicleInventoryService",
	HandlerType: (*VehicleInventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVehicle",
			Handler:    _VehicleInventoryService_CreateVehicle_Handler,
		},
		{
			MethodName: "GetVehicle",
			Handler:    _VehicleInventoryService_GetVehicle_Handler,
		},
		{
			MethodName: "UpdateVehicle",
			Handler:    _VehicleInventoryService_UpdateVehicle_Handler,
		},
		{
			MethodName: "DeleteVehicle",
			Handler:    _VehicleInventoryService_DeleteVehicle_Handler,
		},
		{
			MethodName: "ListVehicles",
			Handler:    _VehicleInventoryService_ListVehicles_Handler,
		},
		{
			MethodName: "UpdateVehicleStatus",
			Handler:    _VehicleInventoryService_UpdateVehicleStatus_Handler,
		},
		{
			MethodName: "CreateLocation",
			Handler:    _VehicleInventoryService_CreateLocation_Handler,
		},
		{
			MethodName: "GetLocation",
			Handler:    _VehicleInventoryService_GetLocation_Handler,
		},
		{
			MethodName: "ListLocations",
			Handler:    _VehicleInventoryService_ListLocations_Handler,
		},
		{
			MethodName: "CreateMaintenanceRecord",
			Handler:    _VehicleInventoryService_CreateMaintenanceRecord_Handler,
		},
		{
			MethodName: "GetMaintenanceRecord",
			Handler:    _VehicleInventoryService_GetMaintenanceRecord_Handler,
		},
		{
			MethodName: "ListMaintenanceRecords",
			Handler:    _VehicleInventoryService_ListMaintenanceRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vehicle_inventory.proto",
}
