// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: vehicle_inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vehicle struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Make              string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model             string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year              int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	LicensePlate      string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CurrentLocationId string                 `protobuf:"bytes,7,opt,name=current_location_id,json=currentLocationId,proto3" json:"current_location_id,omitempty"`
	Mileage           int32                  `protobuf:"varint,8,opt,name=mileage,proto3" json:"mileage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_vehicle_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Vehicle) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Vehicle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Vehicle) GetCurrentLocationId() string {
	if x != nil {
		return x.CurrentLocationId
	}
	return ""
}

func (x *Vehicle) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

type CreateVehicleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Make              string                 `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model             string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Year              int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	LicensePlate      string                 `protobuf:"bytes,4,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CurrentLocationId string                 `protobuf:"bytes,6,opt,name=current_location_id,json=currentLocationId,proto3" json:"current_location_id,omitempty"`
	Mileage           int32                  `protobuf:"varint,7,opt,name=mileage,proto3" json:"mileage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVehicleRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *CreateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateVehicleRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *CreateVehicleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateVehicleRequest) GetCurrentLocationId() string {
	if x != nil {
		return x.CurrentLocationId
	}
	return ""
}

func (x *CreateVehicleRequest) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetVehicleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateVehicleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Make              string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model             string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year              int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	LicensePlate      string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CurrentLocationId string                 `protobuf:"bytes,7,opt,name=current_location_id,json=currentLocationId,proto3" json:"current_location_id,omitempty"`
	Mileage           int32                  `protobuf:"varint,8,opt,name=mileage,proto3" json:"mileage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateVehicleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVehicleRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *UpdateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateVehicleRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *UpdateVehicleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateVehicleRequest) GetCurrentLocationId() string {
	if x != nil {
		return x.CurrentLocationId
	}
	return ""
}

func (x *UpdateVehicleRequest) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

type DeleteVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteVehicleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ListVehiclesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVehiclesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_vehicle_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *ListVehiclesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateVehicleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleStatusRequest) Reset() {
	*x = UpdateVehicleStatusRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleStatusRequest) ProtoMessage() {}

func (x *UpdateVehicleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleStatusRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVehicleStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVehicleStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_vehicle_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Location) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type CreateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationRequest) Reset() {
	*x = CreateLocationRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationRequest) ProtoMessage() {}

func (x *CreateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationRequest.ProtoReflect.Descriptor instead.
func (*CreateLocationRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *CreateLocationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLocationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateLocationRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *GetLocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsRequest) Reset() {
	*x = ListLocationsRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsRequest) ProtoMessage() {}

func (x *ListLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ListLocationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLocationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsResponse) Reset() {
	*x = ListLocationsResponse{}
	mi := &file_vehicle_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResponse) ProtoMessage() {}

func (x *ListLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *ListLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *ListLocationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MaintenanceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Cost          float64                `protobuf:"fixed64,6,opt,name=cost,proto3" json:"cost,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceRecord) Reset() {
	*x = MaintenanceRecord{}
	mi := &file_vehicle_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceRecord) ProtoMessage() {}

func (x *MaintenanceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceRecord.ProtoReflect.Descriptor instead.
func (*MaintenanceRecord) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *MaintenanceRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MaintenanceRecord) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *MaintenanceRecord) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *MaintenanceRecord) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *MaintenanceRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MaintenanceRecord) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *MaintenanceRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateMaintenanceRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Cost          float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMaintenanceRecordRequest) Reset() {
	*x = CreateMaintenanceRecordRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMaintenanceRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMaintenanceRecordRequest) ProtoMessage() {}

func (x *CreateMaintenanceRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMaintenanceRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateMaintenanceRecordRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *CreateMaintenanceRecordRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *CreateMaintenanceRecordRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateMaintenanceRecordRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateMaintenanceRecordRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMaintenanceRecordRequest) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CreateMaintenanceRecordRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetMaintenanceRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMaintenanceRecordRequest) Reset() {
	*x = GetMaintenanceRecordRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaintenanceRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaintenanceRecordRequest) ProtoMessage() {}

func (x *GetMaintenanceRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaintenanceRecordRequest.ProtoReflect.Descriptor instead.
func (*GetMaintenanceRecordRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *GetMaintenanceRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMaintenanceRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaintenanceRecordsRequest) Reset() {
	*x = ListMaintenanceRecordsRequest{}
	mi := &file_vehicle_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaintenanceRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaintenanceRecordsRequest) ProtoMessage() {}

func (x *ListMaintenanceRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaintenanceRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListMaintenanceRecordsRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *ListMaintenanceRecordsRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *ListMaintenanceRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMaintenanceRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMaintenanceRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*MaintenanceRecord   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaintenanceRecordsResponse) Reset() {
	*x = ListMaintenanceRecordsResponse{}
	mi := &file_vehicle_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaintenanceRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaintenanceRecordsResponse) ProtoMessage() {}

func (x *ListMaintenanceRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaintenanceRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListMaintenanceRecordsResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *ListMaintenanceRecordsResponse) GetRecords() []*MaintenanceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListMaintenanceRecordsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_vehicle_inventory_proto protoreflect.FileDescriptor

const file_vehicle_inventory_proto_rawDesc = "" +
	"\n" +
	"\x17vehicle_inventory.proto\x12\x11vehicle_inventory\x1a\x1bgoogle/protobuf/empty.proto\"\xde\x01\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12.\n" +
	"\x13current_location_id\x18\a \x01(\tR\x11currentLocationId\x12\x18\n" +
	"\amileage\x18\b \x01(\x05R\amileage\"\xdb\x01\n" +
	"\x14CreateVehicleRequest\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12#\n" +
	"\rlicense_plate\x18\x04 \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12.\n" +
	"\x13current_location_id\x18\x06 \x01(\tR\x11currentLocationId\x12\x18\n" +
	"\amileage\x18\a \x01(\x05R\amileage\"#\n" +
	"\x11GetVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xeb\x01\n" +
	"\x14UpdateVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12.\n" +
	"\x13current_location_id\x18\a \x01(\tR\x11currentLocationId\x12\x18\n" +
	"\amileage\x18\b \x01(\x05R\amileage\"&\n" +
	"\x14DeleteVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x13ListVehiclesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"d\n" +
	"\x14ListVehiclesResponse\x126\n" +
	"\bvehicles\x18\x01 \x03(\v2\x1a.vehicle_inventory.VehicleR\bvehicles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"D\n" +
	"\x1aUpdateVehicleStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"d\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"a\n" +
	"\x15CreateLocationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\"$\n" +
	"\x12GetLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x14ListLocationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"h\n" +
	"\x15ListLocationsResponse\x129\n" +
	"\tlocations\x18\x01 \x03(\v2\x1b.vehicle_inventory.LocationR\tlocations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xca\x01\n" +
	"\x11MaintenanceRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x01R\x04cost\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xc7\x01\n" +
	"\x1eCreateMaintenanceRecordRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"-\n" +
	"\x1bGetMaintenanceRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"\x1dListMaintenanceRecordsRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"v\n" +
	"\x1eListMaintenanceRecordsResponse\x12>\n" +
	"\arecords\x18\x01 \x03(\v2$.vehicle_inventory.MaintenanceRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x9b\t\n" +
	"\x17VehicleInventoryService\x12T\n" +
	"\rCreateVehicle\x12'.vehicle_inventory.CreateVehicleRequest\x1a\x1a.vehicle_inventory.Vehicle\x12N\n" +
	"\n" +
	"GetVehicle\x12$.vehicle_inventory.GetVehicleRequest\x1a\x1a.vehicle_inventory.Vehicle\x12T\n" +
	"\rUpdateVehicle\x12'.vehicle_inventory.UpdateVehicleRequest\x1a\x1a.vehicle_inventory.Vehicle\x12P\n" +
	"\rDeleteVehicle\x12'.vehicle_inventory.DeleteVehicleRequest\x1a\x16.google.protobuf.Empty\x12_\n" +
	"\fListVehicles\x12&.vehicle_inventory.ListVehiclesRequest\x1a'.vehicle_inventory.ListVehiclesResponse\x12`\n" +
	"\x13UpdateVehicleStatus\x12-.vehicle_inventory.UpdateVehicleStatusRequest\x1a\x1a.vehicle_inventory.Vehicle\x12W\n" +
	"\x0eCreateLocation\x12(.vehicle_inventory.CreateLocationRequest\x1a\x1b.vehicle_inventory.Location\x12Q\n" +
	"\vGetLocation\x12%.vehicle_inventory.GetLocationRequest\x1a\x1b.vehicle_inventory.Location\x12b\n" +
	"\rListLocations\x12'.vehicle_inventory.ListLocationsRequest\x1a(.vehicle_inventory.ListLocationsResponse\x12r\n" +
	"\x17CreateMaintenanceRecord\x121.vehicle_inventory.CreateMaintenanceRecordRequest\x1a$.vehicle_inventory.MaintenanceRecord\x12l\n" +
	"\x14GetMaintenanceRecord\x12..vehicle_inventory.GetMaintenanceRecordRequest\x1a$.vehicle_inventory.MaintenanceRecord\x12}\n" +
	"\x16ListMaintenanceRecords\x120.vehicle_inventory.ListMaintenanceRecordsRequest\x1a1.vehicle_inventory.ListMaintenanceRecordsResponseB@Z>github.com/nurashi/Car-Rental-Platform/vehicle-inventory/protob\x06proto3"

var (
	file_vehicle_inventory_proto_rawDescOnce sync.Once
	file_vehicle_inventory_proto_rawDescData []byte
)

func file_vehicle_inventory_proto_rawDescGZIP() []byte {
	file_vehicle_inventory_proto_rawDescOnce.Do(func() {
		file_vehicle_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vehicle_inventory_proto_rawDesc), len(file_vehicle_inventory_proto_rawDesc)))
	})
	return file_vehicle_inventory_proto_rawDescData
}

var file_vehicle_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_vehicle_inventory_proto_goTypes = []any{
	(*Vehicle)(nil),                        // 0: vehicle_inventory.Vehicle
	(*CreateVehicleRequest)(nil),           // 1: vehicle_inventory.CreateVehicleRequest
	(*GetVehicleRequest)(nil),              // 2: vehicle_inventory.GetVehicleRequest
	(*UpdateVehicleRequest)(nil),           // 3: vehicle_inventory.UpdateVehicleRequest
	(*DeleteVehicleRequest)(nil),           // 4: vehicle_inventory.DeleteVehicleRequest
	(*ListVehiclesRequest)(nil),            // 5: vehicle_inventory.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),           // 6: vehicle_inventory.ListVehiclesResponse
	(*UpdateVehicleStatusRequest)(nil),     // 7: vehicle_inventory.UpdateVehicleStatusRequest
	(*Location)(nil),                       // 8: vehicle_inventory.Location
	(*CreateLocationRequest)(nil),          // 9: vehicle_inventory.CreateLocationRequest
	(*GetLocationRequest)(nil),             // 10: vehicle_inventory.GetLocationRequest
	(*ListLocationsRequest)(nil),           // 11: vehicle_inventory.ListLocationsRequest
	(*ListLocationsResponse)(nil),          // 12: vehicle_inventory.ListLocationsResponse
	(*MaintenanceRecord)(nil),              // 13: vehicle_inventory.MaintenanceRecord
	(*CreateMaintenanceRecordRequest)(nil), // 14: vehicle_inventory.CreateMaintenanceRecordRequest
	(*GetMaintenanceRecordRequest)(nil),    // 15: vehicle_inventory.GetMaintenanceRecordRequest
	(*ListMaintenanceRecordsRequest)(nil),  // 16: vehicle_inventory.ListMaintenanceRecordsRequest
	(*ListMaintenanceRecordsResponse)(nil), // 17: vehicle_inventory.ListMaintenanceRecordsResponse
	(*emptypb.Empty)(nil),                  // 18: google.protobuf.Empty
}
var file_vehicle_inventory_proto_depIdxs = []int32{
	0,  // 0: vehicle_inventory.ListVehiclesResponse.vehicles:type_name -> vehicle_inventory.Vehicle
	8,  // 1: vehicle_inventory.ListLocationsResponse.locations:type_name -> vehicle_inventory.Location
	13, // 2: vehicle_inventory.ListMaintenanceRecordsResponse.records:type_name -> vehicle_inventory.MaintenanceRecord
	1,  // 3: vehicle_inventory.VehicleInventoryService.CreateVehicle:input_type -> vehicle_inventory.CreateVehicleRequest
	2,  // 4: vehicle_inventory.VehicleInventoryService.GetVehicle:input_type -> vehicle_inventory.GetVehicleRequest
	3,  // 5: vehicle_inventory.VehicleInventoryService.UpdateVehicle:input_type -> vehicle_inventory.UpdateVehicleRequest
	4,  // 6: vehicle_inventory.VehicleInventoryService.DeleteVehicle:input_type -> vehicle_inventory.DeleteVehicleRequest
	5,  // 7: vehicle_inventory.VehicleInventoryService.ListVehicles:input_type -> vehicle_inventory.ListVehiclesRequest
	7,  // 8: vehicle_inventory.VehicleInventoryService.UpdateVehicleStatus:input_type -> vehicle_inventory.UpdateVehicleStatusRequest
	9,  // 9: vehicle_inventory.VehicleInventoryService.CreateLocation:input_type -> vehicle_inventory.CreateLocationRequest
	10, // 10: vehicle_inventory.VehicleInventoryService.GetLocation:input_type -> vehicle_inventory.GetLocationRequest
	11, // 11: vehicle_inventory.VehicleInventoryService.ListLocations:input_type -> vehicle_inventory.ListLocationsRequest
	14, // 12: vehicle_inventory.VehicleInventoryService.CreateMaintenanceRecord:input_type -> vehicle_inventory.CreateMaintenanceRecordRequest
	15, // 13: vehicle_inventory.VehicleInventoryService.GetMaintenanceRecord:input_type -> vehicle_inventory.GetMaintenanceRecordRequest
	16, // 14: vehicle_inventory.VehicleInventoryService.ListMaintenanceRecords:input_type -> vehicle_inventory.ListMaintenanceRecordsRequest
	0,  // 15: vehicle_inventory.VehicleInventoryService.CreateVehicle:output_type -> vehicle_inventory.Vehicle
	0,  // 16: vehicle_inventory.VehicleInventoryService.GetVehicle:output_type -> vehicle_inventory.Vehicle
	0,  // 17: vehicle_inventory.VehicleInventoryService.UpdateVehicle:output_type -> vehicle_inventory.Vehicle
	18, // 18: vehicle_inventory.VehicleInventoryService.DeleteVehicle:output_type -> google.protobuf.Empty
	6,  // 19: vehicle_inventory.VehicleInventoryService.ListVehicles:output_type -> vehicle_inventory.ListVehiclesResponse
	0,  // 20: vehicle_inventory.VehicleInventoryService.UpdateVehicleStatus:output_type -> vehicle_inventory.Vehicle
	8,  // 21: vehicle_inventory.VehicleInventoryService.CreateLocation:output_type -> vehicle_inventory.Location
	8,  // 22: vehicle_inventory.VehicleInventoryService.GetLocation:output_type -> vehicle_inventory.Location
	12, // 23: vehicle_inventory.VehicleInventoryService.ListLocations:output_type -> vehicle_inventory.ListLocationsResponse
	13, // 24: vehicle_inventory.VehicleInventoryService.CreateMaintenanceRecord:output_type -> vehicle_inventory.MaintenanceRecord
	13, // 25: vehicle_inventory.VehicleInventoryService.GetMaintenanceRecord:output_type -> vehicle_inventory.MaintenanceRecord
	17, // 26: vehicle_inventory.VehicleInventoryService.ListMaintenanceRecords:output_type -> vehicle_inventory.ListMaintenanceRecordsResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_vehicle_inventory_proto_init() }
func file_vehicle_inventory_proto_init() {
	if File_vehicle_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vehicle_inventory_proto_rawDesc), len(file_vehicle_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vehicle_inventory_proto_goTypes,
		DependencyIndexes: file_vehicle_inventory_proto_depIdxs,
		MessageInfos:      file_vehicle_inventory_proto_msgTypes,
	}.Build()
	File_vehicle_inventory_proto = out.File
	file_vehicle_inventory_proto_goTypes = nil
	file_vehicle_inventory_proto_depIdxs = nil
}
